name: flutter_color
description: Flutter plugin for works with colors schemes like a hex, hsl, xyz and cielab
repository: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/flutter_color
issue_tracker: https://github.com/rbcprolabs/packages.flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+flutter_color%22
version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
